# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslatedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='translated model name')),
            ],
        ),
        migrations.AddField(
            model_name='itemtype',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='rest_app.Parent'),
        ),
        migrations.AlterField(
            model_name='choicemodel',
            name='choice',
            field=models.CharField(choices=[('one', 'Choice One'), ('two', 'Choice Two'), ('three', 'Choice Three')], help_text='Pick One', max_length=10),
        ),
        migrations.AlterField(
            model_name='choicemodel',
            name='name',
            field=models.CharField(help_text='Enter Name', max_length=10),
        ),
    ]
