# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0002_auto_20160922_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlugRefChild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SlugRefParent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_app.SlugModel')),
            ],
        ),
        migrations.AddField(
            model_name='slugrefchild',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_app.SlugRefParent'),
        ),
    ]
